Gohir.1Z013600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.1Z028800.1	IPR027725	Heat shock transcription factor family
Gohir.1Z075600.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.1Z075600.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.1Z084000.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.A01G030700.1	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.A01G052400.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A01G052400.2	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A01G069900.1	IPR014855	Plant transcription factor NOZZLE
Gohir.A01G122400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A01G122700.1	IPR027725	Heat shock transcription factor family
Gohir.A01G134000.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A01G138800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A01G200600.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A01G208500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A01G208600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A01G217700.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A01G226800.1	IPR027759	Trihelix transcription factor GT3
Gohir.A02G018600.1	IPR027725	Heat shock transcription factor family
Gohir.A02G023300.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A02G034500.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.A02G082900.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A02G107600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A02G107600.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A02G107700.1	IPR027725	Heat shock transcription factor family
Gohir.A02G118900.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A02G141200.1	IPR027725	Heat shock transcription factor family
Gohir.A02G145100.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A02G145100.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A02G156100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A02G156300.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A02G158000.1	IPR027725	Heat shock transcription factor family
Gohir.A03G014700.1	IPR027725	Heat shock transcription factor family
Gohir.A03G014700.2	IPR027725	Heat shock transcription factor family
Gohir.A03G014700.3	IPR027725	Heat shock transcription factor family
Gohir.A03G035500.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A03G035500.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A03G076400.1	IPR027725	Heat shock transcription factor family
Gohir.A03G096500.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A03G101500.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A03G101500.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A03G101500.3	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A03G101500.4	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A03G113500.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A03G116700.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A04G012200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A04G035500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A04G048200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A04G052600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A04G091800.1	IPR027759	Trihelix transcription factor GT3
Gohir.A04G095200.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A04G103200.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A04G135300.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A04G147200.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A05G007800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G016200.2	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G023100.1	IPR027725	Heat shock transcription factor family
Gohir.A05G030700.1	IPR027725	Heat shock transcription factor family
Gohir.A05G034900.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G036800.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.A05G057500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G069200.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A05G100400.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G100400.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G100400.3	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G110300.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G110300.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G110300.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G117200.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G117200.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G120600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G137400.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G137400.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G175400.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G196300.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A05G196300.2	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A05G203500.1	IPR027725	Heat shock transcription factor family
Gohir.A05G204500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G252800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G253200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G253300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A05G260200.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A05G299200.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A05G363900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G376800.1	IPR027725	Heat shock transcription factor family
Gohir.A05G405700.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A05G406500.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G406500.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G406500.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A05G406500.4	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G002600.1	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.A06G007800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A06G019400.1	IPR027725	Heat shock transcription factor family
Gohir.A06G020500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A06G026300.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A06G062600.1	IPR027725	Heat shock transcription factor family
Gohir.A06G075000.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G075000.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G075000.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G075000.4	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G075000.5	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G075000.6	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G075000.7	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A06G084300.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.A06G100400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A06G128200.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A06G183300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A06G199000.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A06G199100.1	IPR027725	Heat shock transcription factor family
Gohir.A06G199100.2	IPR027725	Heat shock transcription factor family
Gohir.A06G202500.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A06G202500.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A06G202600.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A07G012200.1	IPR027725	Heat shock transcription factor family
Gohir.A07G013700.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A07G013900.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A07G013900.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A07G030900.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G036100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G040100.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A07G093100.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G112100.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.A07G125100.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G125100.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G148100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G148200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G148300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G148400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G160800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G160800.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G160800.3	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G198800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G198800.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A07G212100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G212200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G212300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A07G215600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G024100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A08G024100.2	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A08G054200.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A08G064100.1	IPR027725	Heat shock transcription factor family
Gohir.A08G064100.2	IPR027725	Heat shock transcription factor family
Gohir.A08G083800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G083800.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G083800.3	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G083800.4	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G083800.5	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G083800.6	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G119900.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.A08G124200.1	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.A08G131200.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A08G144100.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A08G144100.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A08G144100.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A08G146500.1	IPR027759	Trihelix transcription factor GT3
Gohir.A08G151700.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A08G179400.1	IPR027725	Heat shock transcription factor family
Gohir.A08G179400.2	IPR027725	Heat shock transcription factor family
Gohir.A08G213500.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A08G227000.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A08G229100.1	IPR013742	Whirly transcription factor
Gohir.A08G231600.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A08G231600.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A08G241300.1	IPR027725	Heat shock transcription factor family
Gohir.A08G242700.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A08G245400.1	IPR027725	Heat shock transcription factor family
Gohir.A08G252500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A09G003900.1	IPR010684	RNA polymerase II transcription factor SIII, subunit A
Gohir.A09G003900.2	IPR010684	RNA polymerase II transcription factor SIII, subunit A
Gohir.A09G004000.1	IPR010684	RNA polymerase II transcription factor SIII, subunit A
Gohir.A09G021900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A09G072400.1	IPR027725	Heat shock transcription factor family
Gohir.A09G096000.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A09G097800.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.A09G097800.2	IPR032198	E2F transcription factor, CC-MB domain
Gohir.A09G097800.3	IPR032198	E2F transcription factor, CC-MB domain
Gohir.A09G097800.4	IPR032198	E2F transcription factor, CC-MB domain
Gohir.A09G106500.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A09G115000.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A09G127200.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A09G135700.1	IPR027725	Heat shock transcription factor family
Gohir.A09G165500.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A09G165700.1	IPR027759	Trihelix transcription factor GT3
Gohir.A09G179000.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A09G205100.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A09G205100.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A09G206700.1	IPR027725	Heat shock transcription factor family
Gohir.A09G219000.1	IPR027725	Heat shock transcription factor family
Gohir.A09G219600.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.A09G226400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A09G226500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A09G226600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A10G001000.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A10G001000.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A10G004000.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A10G025400.1	IPR027725	Heat shock transcription factor family
Gohir.A10G026500.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A10G027400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A10G033800.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A10G033900.1	IPR027725	Heat shock transcription factor family
Gohir.A10G033900.2	IPR027725	Heat shock transcription factor family
Gohir.A10G052400.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A10G052400.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A10G074600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A10G088200.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A10G091300.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A10G091300.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A10G092000.1	IPR027725	Heat shock transcription factor family
Gohir.A10G113400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A10G115200.1	IPR027725	Heat shock transcription factor family
Gohir.A10G115200.2	IPR027725	Heat shock transcription factor family
Gohir.A10G124000.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A10G173800.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.A10G193700.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A10G193700.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A10G193800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A10G194700.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A10G208000.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A10G208000.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A10G239500.1	IPR033266	Ethylene-responsive transcription factor ABI4
Gohir.A11G010000.1	IPR027725	Heat shock transcription factor family
Gohir.A11G031700.1	IPR027725	Heat shock transcription factor family
Gohir.A11G046500.1	IPR027725	Heat shock transcription factor family
Gohir.A11G088500.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A11G088500.2	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A11G088500.3	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A11G088500.4	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A11G108200.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.A11G125400.1	IPR027725	Heat shock transcription factor family
Gohir.A11G130300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A11G132800.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G132800.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G132800.3	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G139600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A11G195300.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A11G212200.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A11G246200.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G246200.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G246200.3	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G246200.4	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G251800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A11G257800.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A11G287500.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A11G307400.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A12G072900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G072900.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G072900.3	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G072900.4	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G072900.5	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G072900.6	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G073100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A12G073100.2	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A12G080500.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G083800.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A12G123400.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.A12G154800.1	IPR027725	Heat shock transcription factor family
Gohir.A12G166400.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A12G200700.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.A12G207200.1	IPR027725	Heat shock transcription factor family
Gohir.A12G207200.2	IPR027725	Heat shock transcription factor family
Gohir.A12G225800.1	IPR027725	Heat shock transcription factor family
Gohir.A12G225800.2	IPR027725	Heat shock transcription factor family
Gohir.A12G252200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A12G261900.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A12G262700.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A12G262900.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A12G269900.1	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.A13G003600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.A13G027500.1	IPR027725	Heat shock transcription factor family
Gohir.A13G027500.2	IPR027725	Heat shock transcription factor family
Gohir.A13G033800.1	IPR012617	Apoptosis-antagonizing transcription factor, C-terminal
Gohir.A13G035300.1	IPR015660	Achaete-scute transcription factor-related
Gohir.A13G035300.2	IPR015660	Achaete-scute transcription factor-related
Gohir.A13G035300.3	IPR015660	Achaete-scute transcription factor-related
Gohir.A13G035300.4	IPR015660	Achaete-scute transcription factor-related
Gohir.A13G035300.5	IPR015660	Achaete-scute transcription factor-related
Gohir.A13G055300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A13G072000.1	IPR013742	Whirly transcription factor
Gohir.A13G075400.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A13G075400.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A13G109700.1	IPR001193	Membrane-bound transcription factor site-2 protease
Gohir.A13G117100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A13G126400.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.A13G146800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.A13G156700.1	IPR027725	Heat shock transcription factor family
Gohir.A13G156700.2	IPR027725	Heat shock transcription factor family
Gohir.A13G187500.1	IPR027725	Heat shock transcription factor family
Gohir.A13G187500.2	IPR027725	Heat shock transcription factor family
Gohir.A13G187500.3	IPR027725	Heat shock transcription factor family
Gohir.A13G187500.4	IPR027725	Heat shock transcription factor family
Gohir.A13G192100.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A13G192100.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A13G192100.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A13G216700.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A13G216700.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.A13G216700.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D01G041800.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D01G041800.2	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D01G047800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D01G057100.1	IPR014855	Plant transcription factor NOZZLE
Gohir.D01G110500.1	IPR027725	Heat shock transcription factor family
Gohir.D01G121300.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D01G121300.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D01G126700.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D01G126700.2	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D01G128700.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D01G170900.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D01G177700.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D01G181500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D01G190600.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D01G197600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D01G197700.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D01G206600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D01G206600.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D01G216600.1	IPR027759	Trihelix transcription factor GT3
Gohir.D02G022000.1	IPR027725	Heat shock transcription factor family
Gohir.D02G022000.2	IPR027725	Heat shock transcription factor family
Gohir.D02G030600.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D02G041300.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.D02G044600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D02G091100.1	IPR027725	Heat shock transcription factor family
Gohir.D02G094100.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D02G102600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D02G117600.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D02G126300.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D03G022800.1	IPR027725	Heat shock transcription factor family
Gohir.D03G024400.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D03G024500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D03G035500.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D03G051700.1	IPR027725	Heat shock transcription factor family
Gohir.D03G051700.2	IPR027725	Heat shock transcription factor family
Gohir.D03G051700.3	IPR027725	Heat shock transcription factor family
Gohir.D03G051700.4	IPR027725	Heat shock transcription factor family
Gohir.D03G067300.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D03G068800.1	IPR027725	Heat shock transcription factor family
Gohir.D03G068900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D03G132700.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D03G132700.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D03G153000.1	IPR027725	Heat shock transcription factor family
Gohir.D03G154500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D03G173500.1	IPR027725	Heat shock transcription factor family
Gohir.D04G009100.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D04G009100.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D04G009100.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D04G010000.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D04G010000.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D04G039000.1	IPR027725	Heat shock transcription factor family
Gohir.D04G039100.1	IPR027725	Heat shock transcription factor family
Gohir.D04G050800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D04G088000.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D04G088000.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D04G131000.1	IPR027759	Trihelix transcription factor GT3
Gohir.D04G135200.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D04G142600.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D04G178400.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D04G191600.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D05G024600.1	IPR027725	Heat shock transcription factor family
Gohir.D05G032100.1	IPR027725	Heat shock transcription factor family
Gohir.D05G036400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G038300.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.D05G059500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G072100.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D05G100200.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D05G100200.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D05G109300.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D05G109300.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D05G110600.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G110600.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G110600.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G116900.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D05G118100.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D05G121600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G139400.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G139400.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G139400.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G139400.4	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G139400.5	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G164000.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D05G164000.2	IPR015660	Achaete-scute transcription factor-related
Gohir.D05G178500.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G178500.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G178500.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D05G199400.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D05G206600.1	IPR027725	Heat shock transcription factor family
Gohir.D05G207700.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G254700.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G255100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G255300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G262100.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D05G331800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G331800.2	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G331800.3	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G347900.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D05G374500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D06G005600.1	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.D06G017800.1	IPR027725	Heat shock transcription factor family
Gohir.D06G023600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D06G060900.1	IPR027725	Heat shock transcription factor family
Gohir.D06G073800.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D06G081800.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.D06G102500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D06G132200.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D06G190000.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D06G196000.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D06G206300.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D06G206400.1	IPR027725	Heat shock transcription factor family
Gohir.D06G219100.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D06G219200.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D06G219200.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D07G012000.1	IPR027725	Heat shock transcription factor family
Gohir.D07G013500.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D07G016000.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G018400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G031800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G034800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G044200.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D07G097700.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D07G097700.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D07G115600.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D07G115600.2	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D07G115600.3	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D07G129500.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D07G154300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G154400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G154500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G154700.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G164400.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D07G164400.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D07G205300.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D07G205300.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D07G218200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G218300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G218400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D07G222600.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G004000.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G004000.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G008900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G034500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D08G063900.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D08G072600.1	IPR027725	Heat shock transcription factor family
Gohir.D08G093500.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G093500.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G093500.3	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G132800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D08G140800.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.D08G145300.1	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.D08G152700.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D08G165100.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D08G165100.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D08G165100.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D08G165100.4	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D08G167600.1	IPR027759	Trihelix transcription factor GT3
Gohir.D08G172800.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D08G198000.1	IPR027725	Heat shock transcription factor family
Gohir.D08G198000.2	IPR027725	Heat shock transcription factor family
Gohir.D08G198000.3	IPR027725	Heat shock transcription factor family
Gohir.D08G202100.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D08G202100.2	IPR015660	Achaete-scute transcription factor-related
Gohir.D08G202100.3	IPR015660	Achaete-scute transcription factor-related
Gohir.D08G202100.4	IPR015660	Achaete-scute transcription factor-related
Gohir.D08G230600.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D08G241700.1	IPR027725	Heat shock transcription factor family
Gohir.D08G247400.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D08G249400.1	IPR013742	Whirly transcription factor
Gohir.D08G249400.2	IPR013742	Whirly transcription factor
Gohir.D08G252000.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D08G252000.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D08G262000.1	IPR027725	Heat shock transcription factor family
Gohir.D08G263600.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D08G274100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D09G003500.1	IPR010684	RNA polymerase II transcription factor SIII, subunit A
Gohir.D09G021200.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D09G072100.1	IPR027725	Heat shock transcription factor family
Gohir.D09G097600.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D09G097600.2	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D09G103200.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D09G107400.1	IPR027725	Heat shock transcription factor family
Gohir.D09G123400.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D09G137600.1	IPR027725	Heat shock transcription factor family
Gohir.D09G161100.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D09G161300.1	IPR027759	Trihelix transcription factor GT3
Gohir.D09G174500.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D09G198800.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D09G200300.1	IPR027725	Heat shock transcription factor family
Gohir.D09G220800.1	IPR027725	Heat shock transcription factor family
Gohir.D09G221800.1	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.D09G221800.2	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.D09G221800.3	IPR010995	DNA repair Rad51/transcription factor NusA, alpha-helical
Gohir.D09G227200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D09G227300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D09G227400.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D09G227500.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D10G001200.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D10G001200.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D10G001200.3	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D10G004000.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D10G026100.1	IPR027725	Heat shock transcription factor family
Gohir.D10G027100.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D10G027800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D10G034500.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D10G034600.1	IPR027725	Heat shock transcription factor family
Gohir.D10G034600.2	IPR027725	Heat shock transcription factor family
Gohir.D10G034600.3	IPR027725	Heat shock transcription factor family
Gohir.D10G054100.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D10G054100.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D10G076800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D10G096400.1	IPR027725	Heat shock transcription factor family
Gohir.D10G096900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D10G096900.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D10G099700.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D10G099700.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D10G142200.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D10G142200.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D10G151300.1	IPR027725	Heat shock transcription factor family
Gohir.D10G154800.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D10G167700.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D10G180300.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.D10G201000.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D10G201800.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D10G216100.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D10G251400.1	IPR033266	Ethylene-responsive transcription factor ABI4
Gohir.D11G009300.1	IPR027725	Heat shock transcription factor family
Gohir.D11G030400.1	IPR027725	Heat shock transcription factor family
Gohir.D11G049900.1	IPR027725	Heat shock transcription factor family
Gohir.D11G092800.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D11G092800.2	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D11G112700.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.D11G130700.1	IPR027725	Heat shock transcription factor family
Gohir.D11G130700.2	IPR027725	Heat shock transcription factor family
Gohir.D11G136100.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D11G138900.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G138900.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G138900.3	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G145800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D11G145800.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D11G201500.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D11G208800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D11G208800.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D11G210900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D11G245200.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D11G256400.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G256400.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G256400.3	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G256400.4	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G267800.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D11G305400.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D11G322900.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D11G332800.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D11G332800.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D11G336600.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D12G070800.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D12G070800.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D12G070800.3	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D12G070800.4	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D12G070800.5	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D12G070900.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D12G077200.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D12G127000.1	IPR017396	PWRKY transcription factor, group IIc
Gohir.D12G142900.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D12G158000.1	IPR027725	Heat shock transcription factor family
Gohir.D12G169900.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D12G203500.1	IPR008540	BES1/BZR1 plant transcription factor, N-terminal
Gohir.D12G209600.1	IPR027725	Heat shock transcription factor family
Gohir.D12G209600.2	IPR027725	Heat shock transcription factor family
Gohir.D12G228300.1	IPR027725	Heat shock transcription factor family
Gohir.D12G228300.2	IPR027725	Heat shock transcription factor family
Gohir.D12G253300.1	IPR017392	AP2/ERF transcription factor ERF/PTI6
Gohir.D12G263400.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D12G270400.1	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.D12G270400.2	IPR012164	DNA-directed RNA polymerase subunit/transcription factor S
Gohir.D13G003500.1	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D13G003500.2	IPR031112	AP2-like ethylene-responsive transcription factor
Gohir.D13G026300.1	IPR027725	Heat shock transcription factor family
Gohir.D13G026300.2	IPR027725	Heat shock transcription factor family
Gohir.D13G026300.3	IPR027725	Heat shock transcription factor family
Gohir.D13G026300.4	IPR027725	Heat shock transcription factor family
Gohir.D13G026300.5	IPR027725	Heat shock transcription factor family
Gohir.D13G032100.1	IPR012617	Apoptosis-antagonizing transcription factor, C-terminal
Gohir.D13G033700.1	IPR015660	Achaete-scute transcription factor-related
Gohir.D13G067900.1	IPR013742	Whirly transcription factor
Gohir.D13G067900.2	IPR013742	Whirly transcription factor
Gohir.D13G067900.3	IPR013742	Whirly transcription factor
Gohir.D13G067900.4	IPR013742	Whirly transcription factor
Gohir.D13G075600.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D13G075600.2	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D13G109300.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D13G112300.1	IPR001193	Membrane-bound transcription factor site-2 protease
Gohir.D13G112300.2	IPR001193	Membrane-bound transcription factor site-2 protease
Gohir.D13G130100.1	IPR025756	MYB-CC type transcription factor, LHEQLE-containing domain
Gohir.D13G161500.1	IPR027725	Heat shock transcription factor family
Gohir.D13G161500.2	IPR027725	Heat shock transcription factor family
Gohir.D13G194400.1	IPR027725	Heat shock transcription factor family
Gohir.D13G194400.2	IPR027725	Heat shock transcription factor family
Gohir.D13G194400.3	IPR027725	Heat shock transcription factor family
Gohir.D13G194400.4	IPR027725	Heat shock transcription factor family
Gohir.D13G194400.5	IPR027725	Heat shock transcription factor family
Gohir.D13G197500.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D13G197500.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D13G197500.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D13G220300.1	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D13G220300.2	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D13G220300.3	IPR001289	Nuclear transcription factor Y subunit A
Gohir.D13G223800.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D13G226200.1	IPR032198	E2F transcription factor, CC-MB domain
Gohir.D13G226600.1	IPR032198	E2F transcription factor, CC-MB domain
